---
# Enterprise Service Configuration
enterprise_service:
  name: nginx
  
# Monitoring Tool Configuration
monitoring_tool:
  name: node_exporter
  version: 1.7.0
  install_dir: /opt/node_exporter
  service_port: 9100

# Message of the Day
motd_message: "Ansible Managed by patrick"
